---
- name: Create a VM from a template {{ instance_hostname }}.{{ instance_domain }}
  vmware_guest:
    hostname: '{{ VMWARE_HOSTNAME }}'
    username: '{{ VMWARE_USERNAME }}'
    password: '{{ VMWARE_PASSWORD }}'
    datacenter: '{{ VMWARE_DC }}'
    validate_certs: no
    state: poweredon
    name: '{{ instance_hostname }}.{{ instance_domain }}'
    template: '{{ template_name }}'
    folder: '{{ folder }}'
    hardware:
      memory: '{{ instance_memory }}'
      num_cpus: '{{ instance_cpu }}'
    networks:
    - name: '{{ instance_networkname }}'
      ip: '{{ instance_ip }}'
      netmask: '255.255.255.0'
      gateway: '{{ instance_gateway }}'
      domain: '{{ instance_domain }}'
    customization:
      dns_servers:
      - 192.168.77.100
      domain: '{{ instance_domain }}'
      hostname: '{{ instance_hostname }}'
      dns_suffix:
      - '{{ instance_domain }}'
    wait_for_ip_address: yes

